### ISSUE TITLE
Precision

### ISSUE THREAD

**Issue by livingst76** [akinyeke-micheal/motion_calculator#1]
Hello, Michael.
Great work here! It's amazing bringing it all to life.
X doesn't support sending a DM.
I'd suggest you round the results of each operation to address decimal truncation. 
Are you open for a PR so I can help with this?

**Comment by akinyeke-micheal** [comment]
****Thank you for your kind words and feedback! I'm glad you're finding this work helpful.

I appreciate your suggestion to round the results of each operation to address decimal truncation. That's a great idea for improving accuracy. I'm definitely open to collaboration, and I'm grateful for your willingness to contribute.

I've already created a branch named "precision" for this specific enhancement. You can start working on it whenever you're ready. If you have any questions or need guidance on how to get started, feel free to reach out. Let's make this project even better together!

Looking forward to your contributions.

**Comment by livingst76** [comment]
Thank you for the opportunity, Michael.
I won't be available over the weekend, but I will definitely get to you when I'm back.
Have a pleasant weekend!

**Comment by livingst76** [comment]
Hello, Michael.
I'm sorry I couldn't create a PR earlier. I was sick. I just got home today.
Please, do well to correct my errors. This is my first time writing documentation for a PR of this form.
Thank you.
